#!/usr/bin/env bash

set -euo pipefail

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

die() {
  echo "ERROR: $@" >&2
  exit 1
}

check_commands() {
  for cmd in "$@"; do
    has_cmd "$cmd" || die "$cmd not available, quitting."
  done
}

readonly REPO_URL="https://github.com/pervezfunctor/linux-config.git"
readonly DOT_DIR="$HOME/.local/share/linux-config"

dotfiles_clone() {
  [ -d "$DOT_DIR" ] || {
    echo "Directory $DOT_DIR does not exist. Cloning."
    git clone "$REPO_URL" "$DOT_DIR" || die "Failed to clone $REPO_URL"
    return
  }

  [ -z "$(git -C "$DOT_DIR" status --porcelain)" ] && {
    echo "Directory $DOT_DIR is clean. Rebasing."
    git -C "$DOT_DIR" pull --rebase || {
      echo "Rebase failed. Aborting."
      git -C "$DOT_DIR" rebase --abort || die "Failed to abort rebase"
    }
  }

  [ -d "$DOT_DIR" ] || die "Directory $DOT_DIR does not exist. Skipping setup."
}

main() {
  export PATH="$HOME/.bun/bin:$PATH"

  check_commands curl git bash

  has_cmd bun || {
    echo "Bun is not installed. Installing Bun."
    export BUN_INSTALL="$HOME/.bun"
    curl -fsSL https://bun.sh/install | bash
    check_commands "$HOME/.bun/bin/bun" bun
  }

  dotfiles_clone

  (cd "$DOT_DIR/ts" && bun install) || echo "Failed to install dependencies"
  bun run "$DOT_DIR/ts/src/setup.ts" "$@"
}

main "$@"
