[window]
padding = { x = 6, y = 6 }
opacity = 0.8
dynamic_title = true
decorations = "Full"
startup_mode = "Windowed"
dynamic_padding = false

[scrolling]
history = 10000

[font]
normal = { family = "Cascadia Mono NF", style = "Regular" }
bold = { family = "Cascadia Mono NF", style = "Bold" }
italic = { family = "Cascadia Mono NF", style = "Italic" }
bold_italic = { family = "Cascadia Mono NF", style = "Bold Italic" }
size = 11.0
builtin_box_drawing = true

[bell]
duration = 0

[mouse]
hide_when_typing = true

[general]
import = ["dank-theme.toml"]
