border_radius=12
borderpx=3

focused_opacity=1.0
unfocused_opacity=0.97

overviewgappi=12
overviewgappo=12
gappih=8
gappiv=8
gappoh=8
gappov=8

blur=1
blur_optimized=1

shadows = 1
layer_shadows = 1

scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
